# EXPLORATORY DATA ANALYSIS

In [19]:
# Loading the dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv(r"C:\Users\DELL\Documents\EDA_E-Commerce Trends\Cleaned_Superstore.csv")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [20]:
# finding the statistics of all numeric values
df[["Sales","Quantity","Discount","Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [21]:
# Converting Order date & Ship date to data_time 

df["Ship Date"]= pd.to_datetime(df["Ship Date"])
df["Ship Date"]

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Order Date"]

0      2016-11-08
1      2016-11-08
2      2016-06-12
3      2015-10-11
4      2015-10-11
          ...
9989   2014-01-21
9990   2017-02-26
9991   2017-02-26
9992   2017-02-26
9993   2017-05-04
Name: Order Date, Length: 9994, dtype: datetime64[ns]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [23]:
# Examine sales performane acroos categories and Regions
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4635,4636,CA-2017-116288,2017-03-12,2017-03-17,Standard Class,BS-11380,Bill Stewart,Corporate,United States,San Francisco,...,94122,West,OFF-ST-10000736,Office Supplies,Storage,Carina Double Wide Media Storage Towers in Nat...,242.940,3,0.0,9.7176
1249,1250,CA-2017-115602,2017-12-18,2017-12-24,Standard Class,DJ-13630,Doug Jacobs,Consumer,United States,New York City,...,10009,East,FUR-CH-10001708,Furniture,Chairs,Office Star - Contemporary Swivel Chair with P...,1141.938,9,0.1,139.5702
7508,7509,US-2017-161935,2017-07-14,2017-07-18,Standard Class,JL-15835,John Lee,Consumer,United States,Columbus,...,43229,East,OFF-PA-10000605,Office Supplies,Paper,Xerox 1950,9.248,2,0.2,3.3524
6611,6612,CA-2015-107678,2015-04-21,2015-04-28,Standard Class,JK-16090,Juliana Krohn,Consumer,United States,Louisville,...,40214,South,FUR-CH-10001891,Furniture,Chairs,Global Deluxe Office Fabric Chairs,191.960,2,0.0,51.8292
7600,7601,CA-2014-131947,2014-09-17,2014-09-22,Standard Class,JA-15970,Joseph Airdo,Consumer,United States,Springfield,...,97477,West,TEC-MA-10004086,Technology,Machines,Plantronics Single Ear Headset,29.925,5,0.7,-21.9450

In [24]:
# Which category has the highest sales
highest_sales_category = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
highest_sales_category

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [25]:
# Calaculate the average sales per region 
Average_sales_per_region = df.groupby('Region')['Sales'].mean().sort_values(ascending=False)
Average_sales_per_region

Region
South      241.803645
East       238.336110
West       226.493233
Central    215.772661
Name: Sales, dtype: float64

In [26]:
# How does a particular category perform in a particular region
category_region_performance = df.pivot_table(index='Category', columns='Region', values='Sales', aggfunc='sum')
category_region_performance

Region               Central        East       South         West
Category
Furniture        163797.1638  208291.204  117298.684  252612.7435
Office Supplies  167026.4150  205516.055  125651.313  220853.2490
Technology       170416.3120  264973.981  148771.908  251991.8320

In [27]:
# The Average sales for each subcategory in each category
subcategories_per_category = df.pivot_table(index='Sub-Category', columns='Category', values='Sales', aggfunc='mean', fill_value=0)
subcategories_per_category

Category       Furniture  Office Supplies   Technology
Sub-Category
Accessories     0.000000         0.000000   215.974604
Appliances      0.000000       230.755710     0.000000
Art             0.000000        34.068834     0.000000
Binders         0.000000       133.560560     0.000000
Bookcases     503.859633         0.000000     0.000000
Chairs        532.332420         0.000000     0.000000
Copiers         0.000000         0.000000  2198.941618
Envelopes       0.000000        64.867724     0.000000
Fasteners       0.000000        13.936774     0.000000
Furnishings    95.825668         0.000000     0.000000
Labels          0.000000        34.303055     0.000000
Machines        0.000000         0.000000  1645.553313
Paper           0.000000        57.284092     0.000000
Phones          0.000000         0.000000   371.211534
Storage         0.000000       264.590553     0.000000
Supplies        0.000000       245.650200     0.000000
Tables        648.794771         0.000000     0.000000

In [28]:
# Calculate the sum  of sales of sub_category in category 
Sum_sales_sub_category_in_category = df.groupby(['Category', 'Sub-Category'])['Sales'].sum().reset_index()
Sum_sales_sub_category_in_category

           Category Sub-Category        Sales
0         Furniture    Bookcases  114879.9963
1         Furniture       Chairs  328449.1030
2         Furniture  Furnishings   91705.1640
3         Furniture       Tables  206965.5320
4   Office Supplies   Appliances  107532.1610
5   Office Supplies          Art   27118.7920
6   Office Supplies      Binders  203412.7330
7   Office Supplies    Envelopes   16476.4020
8   Office Supplies    Fasteners    3024.2800
9   Office Supplies       Labels   12486.3120
10  Office Supplies        Paper   78479.2060
11  Office Supplies      Storage  223843.6080
12  Office Supplies     Supplies   46673.5380
13       Technology  Accessories  167380.3180
14       Technology      Copiers  149528.0300
15       Technology     Machines  189238.6310
16       Technology       Phones  330007.0540

In [29]:
df.to_csv("EDA_cleaned_Superstore.csv", index=False)